# Generated by Django 5.1.6 on 2025-02-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('ano_publicacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.alunos')),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.livros')),
            ],
        ),
    ]
